name       : kwallet-pam
version    : 5.13.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.1/kwallet-pam-5.13.1.tar.xz : 2166ab166973d6fb7dd635a0a84dc939b41cc80d56116de33cad99f4e5dc55fe
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
