name       : kwallet-pam
version    : 5.11.0
release    : 5
source     :
    - https://download.kde.org/stable/plasma/5.11.0/kwallet-pam-5.11.0.tar.xz : f278b63606168bbfd97658834b59a88465549ffb52607bce73449005a3fb62eb
license    : LGPL-2.1
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
