name       : kwallet-pam
version    : 5.19.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.3/kwallet-pam-5.19.3.tar.xz : 76c8c5f4de02bb33ea3c9766c0cbb04a17b85a668d21c44cebdf594ce03dcc11
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
