name       : kwallet-pam
version    : 5.24.5
release    : 83
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.5/kwallet-pam-5.24.5.tar.xz : 238ed9b80fe3fc72d10a728801c873a0c85db9b9823f3a62ef7d39d6e9a4acea
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
