name       : kwallet-pam
version    : 5.21.2
release    : 64
source     :
    - https://cdn.download.kde.org/stable/plasma/5.21.2/kwallet-pam-5.21.2.tar.xz : 864717b9082e83bf93f0d9fbf8c31adf31c64af2fc4729cbaf67982fba93ff8b
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
