name       : kwallet-pam
version    : 5.16.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.0/kwallet-pam-5.16.0.tar.xz : 498425290ca53b31a82d763d1191b8f0f489311e69f070cda3c4885f951b6581
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
