name       : kwallet-pam
version    : 5.13.5
release    : 24
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.5/kwallet-pam-5.13.5.tar.xz : 4c85cf232ea74695e410766cfbae1522eb314df35f4cb9995b576204a152ad90
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
