name       : kwallet-pam
version    : 5.11.3
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.3/kwallet-pam-5.11.3.tar.xz : 04a6785d0b1e9e716e0f0b8a4625b06a973820efe0551c2b526c6e09c715fa12
license    : LGPL-2.1
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
