name       : kwallet-pam
version    : 5.13.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/plasma/5.13.0/kwallet-pam-5.13.0.tar.xz : ea0fdad521f51d6d98baab8225cfa230975fc3e571cd9a7c7d6912f4c33970e9
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
