name       : kwallet-pam
version    : 5.27.4
release    : 88
source     :
    - https://cdn.download.kde.org/stable/plasma/5.27.4/kwallet-pam-5.27.4.tar.xz : cea13f6b4cc17cb692cf0f94880926e4a072f6af8f4c0bce343ef3d5eafc126c
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
