name       : kwallet-pam
version    : 5.22.5
release    : 72
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.5/kwallet-pam-5.22.5.tar.xz : d8a2a7408e8eefa2b3cc1aa22d130f90ae4bd67c716f290f295a05d5de14320f
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
