name       : kwallet-pam
version    : 5.10.1
release    : 3
source     :
    - https://download.kde.org/stable/plasma/5.10.1/kwallet-pam-5.10.1.tar.xz : 267db5af7e0f13033cf79bbb7fc476c7654bafce7e5a6c654f1e9d0a43383708
license    : LGPL-2.1
component  : desktop.kde
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
