name       : kwallet-pam
version    : 5.16.1
release    : 37
source     :
    - https://download.kde.org/stable/plasma/5.16.1/kwallet-pam-5.16.1.tar.xz : b14119ab3ad42b173441b8a048880ec385605c3051c636649af87644bdab5413
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
