name       : kwallet-pam
version    : 5.23.5
release    : 78
source     :
    - https://cdn.download.kde.org/stable/plasma/5.23.5/kwallet-pam-5.23.5.tar.xz : 89df447e2d79d8fc19225ef57c21abdb56f0adc52536b470f6cf691c79200ab2
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
