name       : kwallet-pam
version    : 5.11.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/kwallet-pam-5.11.1.tar.xz : fed02d1a4592f6b0e80e8f1ddc6a3dfd5c7c019b3def2345fdaa8e2771a3377e
license    : LGPL-2.1
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
