name       : kwallet-pam
version    : 5.20.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.3/kwallet-pam-5.20.3.tar.xz : 44a4b49442dd6b9a313bf2fbe21d6e42fc7dff01fd99ccb166edfbafc277fc02
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
