name       : kwallet-pam
version    : 5.25.3
release    : 84
source     :
    - https://cdn.download.kde.org/stable/plasma/5.25.3/kwallet-pam-5.25.3.tar.xz : 4b8a3388f3496541be376c2b71c0596db1d46bd71041f3eb47ef3b0de82e64c4
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1-only
component  : desktop.kde.core
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
