name       : kwallet-pam
version    : 5.17.5
release    : 46
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/kwallet-pam-5.17.5.tar.xz : c829c7a44408e58beb87c71f5c70bccd349d285c3fcefb16df98bf2f29357fe9
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
