name       : kwallet-pam
version    : 5.17.2
release    : 43
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.2/kwallet-pam-5.17.2.tar.xz : 92d94286e3c4316851f1a43010ce4dc813b6e8f74eb990849f0fa392340fdf7a
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
