name       : kwallet-pam
version    : 5.18.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.1/kwallet-pam-5.18.1.tar.xz : dafced390651e8c5f9572a9def3cdfbab003a32b1ced2711be31b41ab44d9e11
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : LGPL-2.1
component  : desktop.kde.core
optimize   : lto
summary    : KWallet PAM integration
description: |
    KWallet PAM integration.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kwallet-devel
    - libgcrypt-devel
rundeps    :
    - socat
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-pam-security-directory.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
